import fs from "fs-extra";
import path from "path";
import { test, chromium } from "@playwright/test";
import API_Coordinate from "../utils/API_Coordination.json" assert { type: "json" };
test.setTimeout(0);

export const runtime = "nodejs";

const VIEWPORT = {
  width: 800,
  height: 600,
};


const ENTRY = API_Coordinate.data[1];
const GAME_URL = ENTRY.API;
let X = ENTRY.X;
let Y = ENTRY.Y;
let m = ENTRY.active_x??580; //x
let n= ENTRY.active_y??400; //y

let BASE_DURATION_MS = 0;
const REEL_EXTENSION_MS = 2500;

let browser = null;
let context = null;
let running = false;

function countWinningRounds(resultJson) {
  try {
    if (typeof resultJson === "string") {
      resultJson = JSON.parse(resultJson);
    }

    if (!Array.isArray(resultJson)) {
      return 0;
    }

    return Math.max(0, resultJson.length - 1);
  } catch (e) {
    console.error("Invalid result_json:", e);

    return 0;
  }
}

// const sessionHeaders = await page.evaluate(() => {
//   return {
//     "Content-Type": "application/json",
//     Authorization: `Bearer 7648d0fc-2d87-4e84-800b-81381650f123}`, // Example
//   };
// });

async function ensureSession() {
  if (browser && browser.isConnected() && context) {
    return;
  }

  browser = await chromium.launch({
    headless: false,
  });

  context = await browser.newContext({
    viewport: VIEWPORT,
  });
}

test("Spin crawl", async () => {
  
  if (running) {
    return Response.json(
      {
        success: false,
        error: "Recording loop already running",
      },
      { status: 409 },
    );
  }
  
  try {
    running = true;
    const recordingsDir = path.join(process.cwd(), "recordings");

    await fs.ensureDir(recordingsDir);
    await ensureSession();

    const page = await context.newPage();
    await page.goto(GAME_URL, {
      waitUntil: "networkidle",
    });
    fs.writeFile("data/game_report.json", `${Date.now()}\n`);

    await page.evaluate(() => {
        window.addEventListener('mousedown', (e) => {
          console.log('Mouse down at:', e.clientX, e.clientY);
        });
    });
    while (true) {
      if (BASE_DURATION_MS == 0) {
        BASE_DURATION_MS = 3500;
        await page.waitForTimeout(1200);
        console.log("get in game");
        if(ENTRY.portrait){
          await page.waitForTimeout(3000);
        }

        await page.locator('canvas').click({
          position: { x: m, y: n },
          force: true // Bypasses
        });
        continue;
      } else {
        console.log("Waiting for spin...");
        // start push button


        // start recording
        await page.evaluate(() => {
          const canvas = document.querySelector("canvas");

          if (!canvas) {
            throw new Error("Canvas not found");
          }

          const stream = canvas.captureStream(60);

          window.recordedChunks = [];

          window.mediaRecorder = new MediaRecorder(stream, {
            mimeType: "video/webm;codecs=vp9",
          });

          mediaRecorder.ondataavailable = (e) => {
            if (e.data.size > 0) {
              recordedChunks.push(e.data);
            }
          };

          mediaRecorder.start();
        });

        // // wait for POST generated by manual click
        // const responsePromise = page.waitForResponse(
        //   (res) => res.request().method() === "POST",
        //   { timeout: 0 },
        // );
        await page.waitForTimeout(1000);

        await page.locator('canvas').click({
          position: { x: X, y: Y },
          force: true // Bypasses visibility checks if the button is strictly inside the canvas
        });

        const responsePromise = page.waitForResponse(
          (res) =>
            res.request().method() === "POST" && res.url().includes("/v1"),
          { timeout: 0 },
        );

        // const automacaRes = await page.request.post(`${GAME_URL}/v1`, {
        //   headers: sessionHeaders,
        //   data: {
        //     action: "spin",
        //     betLevel: 1,
        //     betSize: 0.2,
        //     game: "",
        //   },
        // });
        // const result = await automacaRes.json();
        // console.log("Automaca response:", result);

        // wait until POST actually happens
        const response = await responsePromise;

        console.log("POST detected");

        // minimum duration
        await page.waitForTimeout(BASE_DURATION_MS);

        let body = null;
        let extraMs = 0;

        try {
          body = await response.json();
        } catch (e) {
          console.error("JSON parse failed:", e);
        }

        if (body) {
          const winAmount = parseFloat(body.data["win_amount"] ?? 0);

          if (!Number.isNaN(winAmount) && winAmount > 0) {
            const winningRounds = countWinningRounds(body.data["result_json"]);

            extraMs = winningRounds * REEL_EXTENSION_MS;
          }
        }

        fs.appendFile("data/game_report.json", `${JSON.stringify(body)},\n`);

        if (extraMs > 0) {
          await page.waitForTimeout(extraMs);
        }

        const base64Video = await page.evaluate(async () => {
          return new Promise((resolve) => {
            mediaRecorder.onstop = async () => {
              const blob = new Blob(recordedChunks, {
                type: "video/webm",
              });

              const arrayBuffer = await blob.arrayBuffer();

              let binary = "";

              const bytes = new Uint8Array(arrayBuffer);

              for (const b of bytes) {
                binary += String.fromCharCode(b);
              }

              resolve(btoa(binary));
            };

            mediaRecorder.stop();
          });
        });

        const buffer = Buffer.from(base64Video, "base64");

        const filename = `spin-${Date.now()}.webm`;

        const fullPath = path.resolve(process.cwd(), "recordings", filename);

        await fs.writeFile(fullPath, buffer);
        console.log("Saved:", filename);
      }
    }
  } catch (e) {
    console.error(e);

    return Response.json(
      {
        success: false,
        error: e.message,
      },
      { status: 500 },
    );
  } finally {
    running = false;
  }
});
