import { chromium, request } from "playwright";
import fs from "fs-extra";
import path from "path";
import { test, expect } from "@playwright/test";

test.setTimeout(0);

export const runtime = "nodejs";

const VIEWPORT = {
  width: 800,
  height: 600,
};
const spinButton = {
  xRatio: 0.5,
  yRatio: 0.5,
  radius: 45,
};
let X=0;
let Y=0;

const OVERLAY_ID = "spin-overlay-btn";

const GAME_URL =
  "https://swiftplay.slotgen.com/uploads/games/en/caribbean_slot-1764907896/index.html?token=7648d0fc-2d87-4e84-800b-81381650f123";

let BASE_DURATION_MS = 0;
const REEL_EXTENSION_MS = 2500;

let browser = null;
let context = null;
let running = false;

function countWinningRounds(resultJson) {
  try {
    if (typeof resultJson === "string") {
      resultJson = JSON.parse(resultJson);
    }

    if (!Array.isArray(resultJson)) {
      return 0;
    }

    return Math.max(0, resultJson.length - 1);
  } catch (e) {
    console.error("Invalid result_json:", e);

    return 0;
  }
}

async function ensureSession() {
  if (browser && browser.isConnected() && context) {
    return;
  }

  browser = await chromium.launch({
    headless: false,
  });

  context = await browser.newContext({
    viewport: VIEWPORT,
  });
}

test("Spin crawl", async () => {
  if (running) {
    return Response.json(
      {
        success: false,
        error: "Recording loop already running",
      },
      { status: 409 },
    );
  }

  try {
    running = true;
    const recordingsDir = path.join(process.cwd(), "recordings");

    await fs.ensureDir(recordingsDir);
    await ensureSession();

    const page = await context.newPage();
    await page.goto(GAME_URL, {
      waitUntil: "networkidle",
    });

    //canvasloaier

    await page.waitForSelector("canvas", {
      timeout: 15000,
    });

    await page.evaluate(({ id }) => {
      const old = document.getElementById(id);

      if (old) {
        old.remove();
      }

      window.__spinRequested = false;
      window.__autoSpin = true;
    }, { id: OVERLAY_ID });

    fs.writeFile("data/game_report.json", `${Date.now()}\n`);

    while (true) {
      if (BASE_DURATION_MS == 0) {
        console.log("get in game");
        BASE_DURATION_MS = 3500;
        await page.waitForTimeout(1200);
        continue;
      } else {
        console.log("Waiting for spin...");

        // start recording
        await page.evaluate(() => {
          const canvas = document.querySelector("canvas");

          if (!canvas) {
            throw new Error("Canvas not found");
          }

          const stream = canvas.captureStream(60);

          window.recordedChunks = [];

          window.mediaRecorder = new MediaRecorder(stream, {
            mimeType: "video/webm;codecs=vp9",
          });

          mediaRecorder.ondataavailable = (e) => {
            if (e.data.size > 0) {
              recordedChunks.push(e.data);
            }
          };

          mediaRecorder.start();
        });

        // // wait for POST generated by manual click
        // const responsePromise = page.waitForResponse(
        //   (res) => res.request().method() === "POST",
        //   { timeout: 0 },
        // );

        const responsePromise = page.waitForResponse(
          (res) =>
            res.request().method() === "POST" && res.url().includes("/v1"),
          { timeout: 0 },
        );

        /// canvas overlay for auto spin

        const canvas = page.locator("canvas");
        const box = await canvas.boundingBox();

        if (!box) {
          throw new Error("Canvas not found");
        }

        const spinX = box.x + box.width ;
        const spinY = box.y + box.height ;

        await page.evaluate(
          ({ id, radius, spinX, spinY }) => {
            let btn = document.getElementById(id);

            if (!btn) {
              btn = document.createElement("button");
              btn.id = id;
              btn.textContent = "SPIN";
              btn.style.position = "fixed";
              btn.style.width = `${radius * 2}px`;
              btn.style.height = `${radius}px`;
              btn.style.border = "2px solid #fff";
              btn.style.borderRadius = "50%";
              btn.style.background = "rgba(220, 20, 60, 0.9)";
              btn.style.color = "#fff";
              btn.style.fontWeight = "700";
              btn.style.fontSize = "14px";
              btn.style.zIndex = "999999";
              btn.style.cursor = "pointer";
              btn.style.pointerEvents = "auto";
              btn.style.boxShadow = "0 8px 20px rgba(0,0,0,0.45)";
              btn.onclick = () => {
                window.__spinRequested = true;
              };

              document.body.appendChild(btn);
            }
            X=120;
            Y=100;
            btn.style.right = `${X}px`;
            btn.style.bottom = `${Y}px`;
          },
          {
            id: OVERLAY_ID,
            radius: spinButton.radius,
            spinX,
            spinY,
          },
        );

        const shouldSpin = await page.evaluate(() => {
          return !!(window.__autoSpin || window.__spinRequested);
        });

        if (!shouldSpin) {
          await page.waitForTimeout(100);
          continue;
        }

        await page.evaluate(() => {
          window.__spinRequested = false;
        });

        await page.mouse.click(X, Y);

        // wait until POST actually happens
        const response = await responsePromise;

        console.log("POST detected");

        // minimum duration
        await page.waitForTimeout(BASE_DURATION_MS);

        let body = null;
        let extraMs = 0;

        try {
          body = await response.json();
        } catch (e) {
          console.error("JSON parse failed:", e);
        }

        if (body) {
          const winAmount = parseFloat(body.data["win_amount"] ?? 0);

          if (!Number.isNaN(winAmount) && winAmount > 0) {
            const winningRounds = countWinningRounds(body.data["result_json"]);

            extraMs = winningRounds * REEL_EXTENSION_MS;
          }
        }

        fs.appendFile("data/game_report.json", `${JSON.stringify(body)},\n`);

        if (extraMs > 0) {
          await page.waitForTimeout(extraMs);
        }

        const base64Video = await page.evaluate(async () => {
          return new Promise((resolve) => {
            mediaRecorder.onstop = async () => {
              const blob = new Blob(recordedChunks, {
                type: "video/webm",
              });

              const arrayBuffer = await blob.arrayBuffer();

              let binary = "";

              const bytes = new Uint8Array(arrayBuffer);

              for (const b of bytes) {
                binary += String.fromCharCode(b);
              }

              resolve(btoa(binary));
            };

            mediaRecorder.stop();
          });
        });

        const buffer = Buffer.from(base64Video, "base64");

        const filename = `spin-${Date.now()}.webm`;

        const fullPath = path.resolve(process.cwd(), "recordings", filename);

        await fs.writeFile(fullPath, buffer);
        console.log("Saved:", filename);
      }
    }
  } catch (e) {
    console.error(e);

    return Response.json(
      {
        success: false,
        error: e.message,
      },
      { status: 500 },
    );
  } finally {
    running = false;
  }
});
