import { chromium } from "playwright";
import fs from "fs-extra";
import path from "path";

export const runtime = "nodejs";

const VIEWPORT = {
  width: 800,
  height: 600,
};

const GAME_URL =
  "https://swiftplay.slotgen.com/uploads/games/en/caribbean_slot-1764907896/index.html?token=7648d0fc-2d87-4e84-800b-81381650f123";

let BASE_DURATION_MS = 0;
const REEL_EXTENSION_MS = 2500;

let browser = null;
let context = null;
let running = false;

function countWinningRounds(resultJson) {
  try {
    if (typeof resultJson === "string") {
      resultJson = JSON.parse(resultJson);
    }

    if (!Array.isArray(resultJson)) {
      return 0;
    }

    return Math.max(0, resultJson.length - 1);
  } catch (e) {
    console.error("Invalid result_json:", e);

    return 0;
  }
}

async function ensureSession() {
  if (browser && browser.isConnected() && context) {
    return;
  }

  browser = await chromium.launch({
    headless: false,
  });

  context = await browser.newContext({
    viewport: VIEWPORT,
  });
}

export async function GET() {
  if (running) {
    return Response.json(
      {
        success: false,
        error: "Recording loop already running",
      },
      { status: 409 },
    );
  }

  try {
    running = true;

    const recordingsDir = path.join(process.cwd(), "recordings");

    await fs.ensureDir(recordingsDir);

    await ensureSession();

    const page = await context.newPage();
    
    await page.goto(GAME_URL, {
      waitUntil: "networkidle",
    });
    fs.writeFile("data/game_report.json", `${Date.now()}\n`);
    
    while (true) {
      if (BASE_DURATION_MS == 0) {
        console.log("get in game");
        BASE_DURATION_MS = 3500;
        await page.waitForTimeout(1200);
        continue;
      } else {
        console.log("Waiting for spin...");
        
        // start recording
        await page.evaluate(() => {
          const canvas = document.querySelector("canvas");
    
          if (!canvas) {
            throw new Error("Canvas not found");
          }
    
          const stream = canvas.captureStream(60);
    
          window.recordedChunks = [];
    
          window.mediaRecorder = new MediaRecorder(stream, {
            mimeType: "video/webm;codecs=vp9",
          });
    
          mediaRecorder.ondataavailable = (e) => {
            if (e.data.size > 0) {
              recordedChunks.push(e.data);
            }
          };
    
          mediaRecorder.start();
        });
        
        // wait for POST generated by manual click
        const responsePromise = page.waitForResponse(
          (res) => res.request().method() === "POST",
          { timeout: 0 },
        );
        test('Send a POST request', async ({ request }) => {
        const response = await request.post('https://reqres.in/api/users', {
          data: {
            name: 'John Doe',
            job: 'Software Engineer'
          }
        });

        // Validate the response
        expect(response.status()).toBe(201);
        const body = await response.json();
        expect(body.name).toBe('John Doe');
      });
        // wait until POST actually happens
        const response = await responsePromise;
        
        console.log("POST detected");
        
        // minimum duration
        await page.waitForTimeout(BASE_DURATION_MS);
        
        let body = null;
        let extraMs = 0;
        
        try {
          body = await response.json();
        } catch (e) {
          console.error("JSON parse failed:", e);
        }

        if (body) {
          const winAmount = parseFloat(body.data["win_amount"] ?? 0);

          if (!Number.isNaN(winAmount) && winAmount > 0) {
            const winningRounds = countWinningRounds(body.data["result_json"]);

            extraMs = winningRounds * REEL_EXTENSION_MS;
          }
        }

        fs.appendFile("data/game_report.json", `${JSON.stringify(body)},\n`);

        if (extraMs > 0) {
          await page.waitForTimeout(extraMs);
        }

        const base64Video = await page.evaluate(async () => {
          return new Promise((resolve) => {
            mediaRecorder.onstop = async () => {
              const blob = new Blob(recordedChunks, {
                type: "video/webm",
              });

              const arrayBuffer = await blob.arrayBuffer();

              let binary = "";

              const bytes = new Uint8Array(arrayBuffer);

              for (const b of bytes) {
                binary += String.fromCharCode(b);
              }

              resolve(btoa(binary));
            };

            mediaRecorder.stop();
          });
        });

        const buffer = Buffer.from(base64Video, "base64");

        const filename = `spin-${Date.now()}.webm`;

        const fullPath = path.resolve(process.cwd(), "recordings", filename);

        await fs.writeFile(fullPath, buffer);
        console.log("Saved:", filename);
      }
    }
  } catch (e) {
    console.error(e);

    return Response.json(
      {
        success: false,
        error: e.message,
      },
      { status: 500 },
    );
  } finally {
    running = false;
  }
}
